# Generated by Django 2.2.5 on 2019-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcapp', '0003_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='enrollment',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='nationality',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
