# Generated by Django 2.2.5 on 2019-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcapp', '0004_auto_20191129_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='serial_no',
            field=models.TextField(blank=True),
        ),
    ]
